[package]
name = "grpc_backend_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cali_core = "0.2.0"
grpc_backend_store = { version = "*", path = "../store" }
